# Generated by Django 5.2.1 on 2025-07-23 05:21

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactus_alter_semester_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_material',
            name='type',
            field=models.CharField(default='material', max_length=100),
        ),
        migrations.AddField(
            model_name='course_textcontent',
            name='type',
            field=models.CharField(default='text content', max_length=100),
        ),
        migrations.AddField(
            model_name='course_video',
            name='type',
            field=models.CharField(default='video', max_length=100),
        ),
        migrations.AlterField(
            model_name='semester',
            name='university',
            field=models.ForeignKey(blank=True, default=api.models.get_default_university, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, default=api.models.get_default_university, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
