# Generated by Django 5.2.1 on 2025-07-25 12:33

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_material_type_course_textcontent_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, default=api.models.get_default_university, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
