# Generated by Django 5.2.1 on 2025-08-08 05:14

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_blog_category_alter_teacher_university_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, default=api.models.get_default_university, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
    ]
