# Generated by Django 5.2.1 on 2025-08-19 08:40

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_course_to_faculty_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course_to_faculty',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='university',
            field=models.ForeignKey(blank=True, default=api.models.get_default_university, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.university'),
        ),
        migrations.RemoveField(
            model_name='course_to_faculty',
            name='course',
        ),
        migrations.AddField(
            model_name='course_to_faculty',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.course'),
        ),
    ]
